name: kicad-exports

on:
  push:
    branches: [ANA, BOOST, BUS, CONN, ESP, POS, LOG, LORA, QWIIC, SAMD, UART, WING, ZPM]
    paths:
    - '**.sch'
    - '**.kicad_pcb'
  pull_request:
    branches: [ANA, BOOST, BUS, CONN, ESP, POS, LOG, LORA, QWIIC, SAMD, UART, WING, ZPM]
    paths:
    - '**.sch'
    - '**.kicad_pcb'
      
jobs:
    exports:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: get current BRANCH and VERSION
        run: |
          BRANCH=`git branch --show-current`
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          VERSION=`grep -E '(rev v[0-9]\.[0-9])' $BRANCH/ProMicro_$BRANCH.kicad_pcb`
          echo "VERSION=${VERSION:9:-1}" >> $GITHUB_ENV
      - uses: nerdyscout/kicad-exports@v2.2
        with:
          config: config.kibot.yaml
          board: ${{ env.BRANCH }}/ProMicro_${{ env.BRANCH }}.kicad_pcb
          schema: ${{ env.BRANCH }}/ProMicro_${{ env.BRANCH }}.sch
          dir: ${{ env.BRANCH }}
      - name: git commit && git push
        uses: stefanzweifel/git-auto-commit-action@force-tags
        with:
          # Optional but recommended, defaults to "Apply automatic changes"
          commit_message: 'update autogenerated files'
          # Optional branch to push to, defaults to the current branch
          branch: docs
          # Optional options appended to `git-commit`
          # See https://git-scm.com/docs/git-commit for a list of available options
          # commit_options: '--no-verify --signoff'
          # Optional glob pattern of files which should be added to the commit
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: ${{ env.BRANCH }}/docs/* ${{ env.BRANCH }}/gerbers/* ${{ env.BRANCH }}/cad/*
          # Optional local file path to the repository
          # repository: .
          # Optional commit user and author settings
          commit_user_name: ci
          commit_user_email: ci@github
          commit_author: kicad-exports
          # Optional tag message 
          # Action will create and push a new tag to the remote repository and the defined branch
          # tagging_message: ${{ env.BRANCH }}_${{ env.VERSION }}
          # Optional options appended to `git-push`
          # See git-push documentation for details: https://git-scm.com/docs/git-push#_options
          push_options: '--tags --force'
          # Optional: Disable dirty check and always try to create a commit and push
          skip_dirty_check: true
          # Optional: Allows you to update how the repo is checked out
          # checkout_options: '-q --force -b'
