name: kicad-exports

#on:
#  push:
#    paths:
#    - '**.sch'
#    - '**.kicad_pcb'
#  pull_request:
#    paths:
#      - '**.sch'
#      - '**.kicad_pcb'

jobs:
    docs:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: nerdyscout/kicad-exports@v2.0
        with:
          config: docs.kiplot.yaml
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs
        
    fabrications:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: nerdyscout/kicad-exports@v2.0
        with:
          config: fabrications.kiplot.yaml
      - uses: actions/upload-artifact@v2
        with:
          name: fabrications
          path: gerbers

    bom:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: nerdyscout/kicad-exports@v2.0
        with:
          config: bom.kiplot.yaml
      - uses: actions/upload-artifact@v2
        with:
          name: bom
          path: docs/bom
        
    plot:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: nerdyscout/kicad-exports@v2.0
        with:
          config: plot.kiplot.yaml
      - uses: actions/upload-artifact@v2
        with:
          name: plot
          path: docs/img

    push:
      runs-on: ubuntu-latest
      needs: [docs, fabrications, bom, plot]
      steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: docs
      - uses: actions/download-artifact@v2
        with:
          name: fabrications
      - uses: actions/download-artifact@v2
        with:
          name: bom    
      - uses: actions/download-artifact@v2
        with:
          name: plot
      - run: apt-get install -y tree && tree
      - name: git commit && git push 
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'update autogenerated files'
          name: kicad-exports
          rebase: 'true'
          files: docs/* gerbers/*
