name: kicad-exports

on:
  push:
    branches: [ANA, BOOST, BUS, CONN, GPS, LOG, LORA, QWIIC, SAMD, TEST, UART, WING, ZPM]
#    paths:
#    - '**.sch'
#    - '**.kicad_pcb'
  pull_request:
    branches: [ANA, BOOST, BUS, CONN, GPS, LOG, LORA, QWIIC, SAMD, TEST, UART, WING, ZPM]
#    paths:
#      - '**.sch'
#      - '**.kicad_pcb'
      
jobs:
    exports:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1
      - run: echo ::set-output name=current::${BRANCH_NAME}
        id: branch
      - uses: nerdyscout/kicad-exports@v2.0
        with:
          config: ${{ steps.branch.outputs.current }}/config.kiplot.yaml
          board: ${{ steps.branch.outputs.current }}/ProMicro_TEST.kicad_pcb
          schema: ${{ steps.branch.outputs.current }}/ProMicro_TEST.sch
          dir: ${{ steps.branch.outputs.current }}
      - name: git commit && git push 
        uses: github-actions-x/commit@v2.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'update autogenerated files'
          push-branch: ${{ steps.branch.outputs.current }}
          name: kicad-exports
          rebase: 'true'
          files: ${{ steps.branch.outputs.current }}/docs/* ${{ steps.branch.outputs.current }}/gerbers/*

