name: kicad-exports

on:
  push:
    branches: [ANA, BOOST, BUS, CONN, ESP32, POS, LOG, LORA, QWIIC, SAMD, UART, WING, ZPM]
    paths:
    - '**.sch'
    - '**.kicad_pcb'
  pull_request:
    branches: [ANA, BOOST, BUS, CONN, ESP32, POS, LOG, LORA, QWIIC, SAMD, UART, WING, ZPM]
    paths:
    - '**.sch'
    - '**.kicad_pcb'
      
jobs:
    exports:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1
      - run: echo ::set-output name=current::${BRANCH_NAME}
        id: branch
      - uses: nerdyscout/kicad-exports@v2.1
        with:
          config: ${{ steps.branch.outputs.current }}/config.kiplot.yaml
          board: ${{ steps.branch.outputs.current }}/ProMicro_${{ steps.branch.outputs.current }}.kicad_pcb
          schema: ${{ steps.branch.outputs.current }}/ProMicro_${{ steps.branch.outputs.current }}.sch
          dir: ${{ steps.branch.outputs.current }}
#      - name: git commit && git push 
#        uses: github-actions-x/commit@v2.7
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          commit-message: 'update autogenerated files'
#          push-branch: ${{ steps.branch.outputs.current }}
#          name: kicad-exports
#          rebase: 'true'
#          files: ${{ steps.branch.outputs.current }}/docs/* ${{ steps.branch.outputs.current }}/gerbers/*

      - name: regex tag
        uses: christophebedard/tag-version-commit@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
#          version_assertion_command: 'grep -E '^(Rev \"v)([0-9]\.[0-9])\"$' ProMicro_${{ steps.branch.outputs.current }}.sch'
          version_assertion_command: 'grep -E '([0-9]\.[0-9])' ProMicro_${{ steps.branch.outputs.current }}.sch'

      - name: git commit && git push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional but recommended, defaults to "Apply automatic changes"
          commit_message: 'update autogenerated files'
          # Optional branch to push to, defaults to the current branch
          branch: ${{ steps.branch.outputs.current }}
          # Optional options appended to `git-commit`
          # See https://git-scm.com/docs/git-commit for a list of available options
          # commit_options: '--no-verify --signoff'
          # Optional glob pattern of files which should be added to the commit
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: ${{ steps.branch.outputs.current }}/docs/* ${{ steps.branch.outputs.current }}/gerbers/*
          # Optional local file path to the repository
          # repository: .
          # Optional commit user and author settings
          commit_user_name: ci
          commit_user_email: ci@github
          commit_author: kicad-exports
          # Optional tag message 
          # Action will create and push a new tag to the remote repository and the defined branch
          tagging_message: ${{ steps.branch.outputs.current }}_
          # Optional options appended to `git-push`
          # See git-push documentation for details: https://git-scm.com/docs/git-push#_options
          push_options: '--tags --force'
          # Optional: Disable dirty check and always try to create a commit and push
          skip_dirty_check: true
          # Optional: Allows you to update how the repo is checked out
          # checkout_options: '-q --force -b'
